version: "2.29.2"

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "142398749lzr"
    volumes:
      - "/root/opt/mysql/conf:/etc/mysql/conf.d"
      - "/root/opt/mysql/logs:/var/log/mysql"
      - "/root/opt/mysql/data:/root/opt/mysql/data"
    networks:
      - byteoj
  byteoj:
    build:
      context: /root/opt
      dockerfile: Dockerfile
    container_name: byteoj
    ports:
      - "7091:7091"
    volumes:
      - "/root/opt/mysql/data/backup:/root/opt/mysql/data/backup"
    networks:
      - byteoj
    depends_on:
      - mysql
  nginx:
    image: nginx
    container_name: nginx
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UFT-8
      - LANGUAGE=C.UTF-8
    ports:
      - "80:80"
      - "443:443"
      - "10002:10002"
    volumes:
      - "/root/www/wwwroot/byteoj/dist:/usr/share/nginx/html/byteoj/dist"
      - "/root/www/wwwroot/byteojAdmin/dist:/usr/share/nginx/html/byteojAdmin/dist"
      - "/root/www/wwwroot/XBT/dist:/usr/share/nginx/html/XBT/dist"
      - "/root/ssl:/root/ssl"
      - "/root/opt/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/root/www/wwwroot/index/dist:/usr/share/nginx/html/index/dist"
    networks:
      - byteoj
  redis:
    image: redis:5.0.14
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "/root/opt/redis/data:/data"
    restart: always
    command: redis-server --requirepass ",s8ab3kz9U4J20[wRFOM!Vg(cu7S#1W@"
    privileged: true
    networks:
      - byteoj
networks:
  byteoj:
    name: byteoj
