spring:
  mail:
    host: smtp.qq.com # 指定邮件服务器的主机名，这里默认是smtp.qq.com，表示使用的是腾讯的SMTP服务器。
    port: 587 # 456也行
    username: # xxxx@qq.com  这里是发送者
    password:  # 授权码
    properties: # 其他配置
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 指定SSL Socket工厂类，用于创建加密的邮件连接。
          auto: true # 设置为true表示启用自动连接。
        starttls: # 配置STARTTLS加密连接
          enable: true # 设置为true表示启用STARTTLS。
          required: true # 设置为true表示STARTTLS是必需的，如果不可用，则会抛出异常。
    default-encoding: UTF-8 # 设置邮件内容的默认编码格式为UTF-8 默认就是UTF-8
  main:
    #    解决升级Spring Boot2.6后,因依赖循环引用导致启动时报错的问题
    allow-circular-references: true
  profiles:
    active: dev
  application:
    name: backend
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:设定数据库端口/你的数据库名?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: # 你的mysql数据库的用户名
    password: # 你的mysql数据库的密码

    # session失效时间(分钟)和存储工作配置
    # session:
    # timeout: 86400
    # store-type: redis # 默认为none
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis配置
  redis:
    # 端口
    port: # 你的redis端口号，默认为6379
    host: 127.0.0.1
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: # 你的redis的密码，没有就删除本行
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20

  # RabbitMQ 配置，尚未使用，后面使用会启用
  #  rabbitmq:
  #    host: localhost
  #    port: 15672
  #    username: guest
  #    password: guest
  #    virtual-host: /
  #    # 开启消息发送确认
  #    publisher-returns: true
  #    listener:
  #      simple:
  #        acknowledge-mode: manual
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  # 端口
  port: # 自行修改项目启动的端口号，默认为80端口
  address: 0.0.0.0
  # 自定义路径
  servlet:
    context-path: /api
#    session:
#      cookie:
#        domain: localhost
mybatis-plus:
  configuration:
    #    会默认将下滑线转换成驼峰式
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  # 日志持久化存储文件 nohup java -jar xxx.jar > /dev/null 2>&1 &
  file:
    name: ./log/spring.log
  # 日志分割
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.txt
      max-file-size: 1MB
aliyun:
  oss:
    endpoint: # 阿里云OSS地址，这里看你自己的OSS选择
    accessKeyId: # 阿里云OSS账号
    accessKeySecret:  # 阿里云OSS密钥
    #        bucket可以由控制台创建，也可以使用java代码创建
    bucketName:  #阿里云OSS上的存储块bucket名字

interfaceAccess:
  second: 60        # 接口访问second秒内最多只能访问requestCount次
  requestCount: 60    # 请求3次
  lockTime: 60      # 禁用时长--单位/秒

ROLE_MAX:
  UUID: 9
JUDGE_URL:
  URL: # 你的沙箱接口地址，此处就不暴露自己的了

GITHUB:
  ClientId: # GITHUB授权登录在自己github得到的ClientId
  ClientSecret: # GITHUB授权登录在自己github得到的ClientSecret