-- ========================================
-- 相似度团伙表 (PostgreSQL)
-- 存储预计算的抄袭团伙信息
-- ========================================

CREATE TABLE IF NOT EXISTS similarity_cluster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id BIGINT NOT NULL,
    problem_index VARCHAR(10) NOT NULL,
    cluster_id INTEGER NOT NULL,
    cluster_size INTEGER NOT NULL,
    avg_similarity DOUBLE PRECISION NOT NULL,
    user_uuids TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uk_competition_problem_cluster UNIQUE(competition_id, problem_index, cluster_id)
);

-- 添加字段注释
COMMENT ON TABLE similarity_cluster IS '相似度团伙表,预计算的抄袭团伙信息';
COMMENT ON COLUMN similarity_cluster.id IS '主键ID';
COMMENT ON COLUMN similarity_cluster.competition_id IS '竞赛ID';
COMMENT ON COLUMN similarity_cluster.problem_index IS '题目索引(A,B,C...)';
COMMENT ON COLUMN similarity_cluster.cluster_id IS '团伙编号(1,2,3...)';
COMMENT ON COLUMN similarity_cluster.cluster_size IS '团伙人数';
COMMENT ON COLUMN similarity_cluster.avg_similarity IS '平均相似度';
COMMENT ON COLUMN similarity_cluster.user_uuids IS '成员UUID列表(JSON数组)';
COMMENT ON COLUMN similarity_cluster.created_at IS '创建时间';

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_cluster_competition_problem ON similarity_cluster(competition_id, problem_index);
CREATE INDEX IF NOT EXISTS idx_cluster_size ON similarity_cluster(cluster_size DESC);

-- ========================================
-- 说明:
-- 1. 使用 UNIQUE 约束避免重复计算
-- 2. user_uuids 存储为 JSON 数组: [1001,1002,1003]
-- 3. 移除 GIN 索引,因为 TEXT 类型不支持 jsonb_path_ops
-- 4. 查询用户所属团伙时,使用 LIKE '%uuid%' 模糊匹配
-- ========================================
