-- ========================================
-- Embedding 任务队列表 (PostgreSQL)
-- 用于持久化任务状态,支持断点续传
-- ========================================

CREATE TABLE IF NOT EXISTS embedding_task_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id BIGINT NOT NULL,
    batch_index INTEGER NOT NULL,
    total_batches INTEGER NOT NULL,
    user_uuids TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

-- 添加字段注释
COMMENT ON TABLE embedding_task_queue IS 'Embedding任务队列,用于持久化任务状态,支持断点续传';
COMMENT ON COLUMN embedding_task_queue.id IS '主键ID';
COMMENT ON COLUMN embedding_task_queue.competition_id IS '竞赛ID';
COMMENT ON COLUMN embedding_task_queue.batch_index IS '批次索引';
COMMENT ON COLUMN embedding_task_queue.total_batches IS '总批次数';
COMMENT ON COLUMN embedding_task_queue.user_uuids IS '用户UUID列表(JSON数组)';
COMMENT ON COLUMN embedding_task_queue.status IS '状态: PENDING-待处理, PROCESSING-处理中, COMPLETED-已完成, FAILED-失败';
COMMENT ON COLUMN embedding_task_queue.retry_count IS '重试次数';
COMMENT ON COLUMN embedding_task_queue.error_message IS '错误信息';
COMMENT ON COLUMN embedding_task_queue.created_at IS '创建时间';
COMMENT ON COLUMN embedding_task_queue.updated_at IS '更新时间';
COMMENT ON COLUMN embedding_task_queue.completed_at IS '完成时间';

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_embedding_task_status ON embedding_task_queue(status);
CREATE INDEX IF NOT EXISTS idx_embedding_task_competition ON embedding_task_queue(competition_id);
CREATE INDEX IF NOT EXISTS idx_embedding_task_created ON embedding_task_queue(created_at);

-- ========================================
-- 说明:
-- 1. 定时任务先把所有批次插入这张表(status=PENDING)
-- 2. 另一个定时任务每次取几条PENDING的记录,更新为PROCESSING,发到MQ
-- 3. 消费者处理完更新为COMPLETED
-- 4. 如果中途重启,重启后继续取PENDING的记录处理
-- 5. 失败的记录可以重试(retry_count)
-- ========================================
